// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKq0qe5Vt1djRdf2XpHPsI8HATJ6ni3VI',
    appId: '1:850803122628:web:db1a507314436def6f8491',
    messagingSenderId: '850803122628',
    projectId: 'flutter-study-app-61057',
    authDomain: 'flutter-study-app-61057.firebaseapp.com',
    storageBucket: 'flutter-study-app-61057.appspot.com',
    measurementId: 'G-BEQK0W8ZDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr28Qytf7abWkrrMzocdXgl-Pf3C6cWxY',
    appId: '1:850803122628:android:ca3f018391b06b2a6f8491',
    messagingSenderId: '850803122628',
    projectId: 'flutter-study-app-61057',
    storageBucket: 'flutter-study-app-61057.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTBSYw8IG1Rdc047NbEbb2lzsJj_UzBGg',
    appId: '1:850803122628:ios:cb829d5cff2741d06f8491',
    messagingSenderId: '850803122628',
    projectId: 'flutter-study-app-61057',
    storageBucket: 'flutter-study-app-61057.appspot.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTBSYw8IG1Rdc047NbEbb2lzsJj_UzBGg',
    appId: '1:850803122628:ios:7e02a136147f5e726f8491',
    messagingSenderId: '850803122628',
    projectId: 'flutter-study-app-61057',
    storageBucket: 'flutter-study-app-61057.appspot.com',
    iosBundleId: 'com.example.flutterStudyApp.RunnerTests',
  );
}
